[versions]
arrow = "2.2.1.1"
awsLambdaEvents = "3.16.1"
awsSdk = "2.41.14"
com-google-devtools-ksp = "2.3.4"
forkhandles = "2.25.0.0"
graphqlKotlin = "8.8.1"
hamkrest = "1.8.0.0"
http4k-standards = "1.3.0.0"
jackson = "2.21.0"
jsoup = "1.22.1"
junit = "6.0.2"
kotlin = "2.3.0"
ktor = "3.4.0"
logback = "1.5.26"
micronaut = "4.10.14"
micronaut-platform = "4.10.7"
micronautApplication = "4.6.1"
micronautKotlin = "4.7.0"
micronautSerde = "2.16.2"
mockk = "1.14.7"
nimbusJoseJwt = "10.7"
pulumi = "1.20.0"
pulumiAws = "7.16.0"
pulumiAwsNative = "1.50.0"
quarkus = "3.31.0"
shadow = "9.3.1"
springBoot = "4.0.2"
typeflows = "0.32.0-beta"
version-catalog-update = "1.0.1"
versions = "0.53.0"

[libraries]
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
aws-lambda-java-events = { module = "com.amazonaws:aws-lambda-java-events", version.ref = "awsLambdaEvents" }
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "awsSdk" }
aws-sdk-dynamodb = { module = "software.amazon.awssdk:dynamodb", version.ref = "awsSdk" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awsSdk" }
forkhandles-result4k = { module = "dev.forkhandles:result4k", version.ref = "forkhandles" }
forkhandles-time4k = { module = "dev.forkhandles:time4k", version.ref = "forkhandles" }
graphql-kotlin-schema-generator = { module = "com.expediagroup:graphql-kotlin-schema-generator", version.ref = "graphqlKotlin" }
hamkrest = { module = "com.natpryce:hamkrest", version.ref = "hamkrest" }
http4k-standards = { module = "org.http4k.standards:typeflows", version.ref = "http4k-standards" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client", version.ref = "micronaut" }
micronaut-http-validation = { module = "io.micronaut:micronaut-http-validation", version.ref = "micronaut" }
micronaut-kotlin-runtime = { module = "io.micronaut.kotlin:micronaut-kotlin-runtime", version.ref = "micronautKotlin" }
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut-platform" }
micronaut-runtime = { module = "io.micronaut:micronaut-runtime", version.ref = "micronaut" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson", version.ref = "micronautSerde" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor", version.ref = "micronautSerde" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbusJoseJwt" }
pulumi-aws = { module = "com.pulumi:aws", version.ref = "pulumiAws" }
pulumi-aws-native = { module = "com.pulumi:aws-native", version.ref = "pulumiAwsNative" }
pulumi-core = { module = "com.pulumi:pulumi", version.ref = "pulumi" }
quarkus-undertow = { module = "io.quarkus:quarkus-undertow", version.ref = "quarkus" }
quarkus-universe-bom = "io.quarkus:quarkus-universe-bom:3.30.8"
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
typeflows-github = { module = "io.typeflows:typeflows-github", version.ref = "typeflows" }
typeflows-github-marketplace = { module = "io.typeflows:typeflows-github-marketplace", version.ref = "typeflows" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronautApplication" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
typeflows = { id = "io.typeflows", version.ref = "typeflows" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }

[bundles]
junit-testing = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
]
