on:
  pull_request:
    types: [labeled]
    branches:
      - auto/*
jobs:
  handle-pr-for-http4k-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}
      - name: Automatically Merge
        uses: plm9606/automerge_actions@1.2.2
        with:
          label-name: automerge
          reviewers-number: 0
          merge-method: squash
          auto-delete: true
          github-token: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}
